import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Web3ModalProvider from "./Web3Modal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Spin Playground",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Web3ModalProvider>{children}</Web3ModalProvider>
            </body>
        </html>
    );
}
