
test-contracts:
	@npx hardhat test --verbose

deploy-contracts:
	@npx hardhat ignition deploy ignition/modules/DummyContract.ts --network sepolia --verify

set-etherscan-key:
	@npx hardhat vars set ETHERSCAN_API_KEY