
test-contracts:
	@npx hardhat test --verbose

deploy-contracts:
	@npx hardhat ignition deploy ignition/modules/DummyContract.ts --network sepolia --verify

deploy-contracts-reset:
	@npx hardhat ignition deploy ignition/modules/DummyContract.ts --network sepolia --reset --verify